bucket         = "danielricci-terraform-state"
key            = "iac/local/terraform.tfstate"
region         = "us-east-1"
profile        = "danielricci"
dynamodb_table = "tflock-danielricci-terraform-state"